site_name: Developer Handbook
site_url: https://nationalarchives.github.io/developer-handbook/
repo_url: https://github.com/nationalarchives/developer-handbook
dev_addr: 127.0.0.1:8888
nav:
  - Home: index.md
  - Getting started: getting-started.md
  - Technology:
    - technology/index.md
    - HTML: technology/html.md
    - Python: technology/python.md
    - JavaScript: technology/javascript.md
    - TypeScript: technology/typescript.md
    - CSS: technology/css.md
    - Docker: technology/containers.md
    - Nginx: technology/nginx.md
    - Postgres: technology/postgres.md
  - Ways of working:
    - ways-of-working/index.md
    - Service standard: ways-of-working/service-standard.md
    - Version control: ways-of-working/version-control.md
    - Testing: ways-of-working/testing.md
    - APIs: ways-of-working/api.md
    - Browser support: ways-of-working/browser-support.md
    - Accessibility: ways-of-working/accessibility.md
    - Deployment: ways-of-working/deployment.md
  - Projects:
    - projects/index.md
    - Setup: projects/setup.md
  - Third party:
    - third-party/index.md
    - NPMJS: third-party/npmjs.md
    - PyPI: third-party/pypi.md
    - GitHub: third-party/github.md
    - Docker registries: third-party/docker-registries.md
    - Analytics: third-party/analytics.md
    - AWS: third-party/aws.md
    - YouTube: third-party/youtube.md
  - Organisation:
    - organisation/index.md
    - Technical Architects Group: organisation/technical-architects-group.md
    - Technical Governance Board: organisation/technical-governance-board.md
  - Resources:
    - resources/index.md
    - Frontend styles: resources/frontend-styles.md
    - Frontend implementations: resources/frontend-implementations.md
    - Docker images: resources/docker-images.md
theme:
  name: material
  logo: assets/tna-horizontal-logo-inverted.svg
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - toc.integrate
  palette:
    - primary: custom
extra_css:
  - stylesheets/extra.css
plugins:
  - search
markdown_extensions:
  - abbr
  - attr_list
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
