site_name: Engineering Handbook - The National Archives
site_url: https://nationalarchives.github.io/engineering-handbook/
repo_url: https://github.com/nationalarchives/engineering-handbook
dev_addr: localhost:8888
use_directory_urls: true
nav:
  - Home: index.md
  - Getting started:
    - getting-started/index.md
    - Tools: getting-started/tools.md
    - Services: getting-started/services.md
    - Communication: getting-started/communication.md
  - Technology:
    - technology/index.md
    - Frontend:
      - HTML: technology/html.md
      - JavaScript: technology/javascript.md
      - CSS: technology/css.md
    - Backend:
      - Python: technology/python.md
      - Scala: technology/scala.md
    - Database:
      - Postgres: technology/postgres.md
    - Deployment:
      - Docker: technology/containers.md
      - Terraform: technology/terraform.md
      - Nginx: technology/nginx.md
    - Cloud:
      - Amazon Web Services (AWS): technology/aws.md
  - Ways of working:
    - ways-of-working/index.md
    - Service standard: ways-of-working/service-standard.md
    - Progressive enhancement: ways-of-working/progressive-enhancement.md
    - Version control: ways-of-working/version-control.md
    - Documentation: ways-of-working/documentation.md
    - Testing: ways-of-working/testing.md
    - APIs: ways-of-working/api.md
    - URLs: ways-of-working/url.md
    - Browser support: ways-of-working/browser-support.md
    - Accessibility: ways-of-working/accessibility.md
    - Deployment: ways-of-working/deployment.md
    - Definition of done: ways-of-working/definition-of-done.md
  - Third party:
    - third-party/index.md
    - NPMJS: third-party/npmjs.md
    - PyPI: third-party/pypi.md
    - GitHub: third-party/github.md
    - Docker registries: third-party/docker-registries.md
    - Analytics: third-party/analytics.md
    - YouTube: third-party/youtube.md
  - Organisation:
    - organisation/index.md
    - Technical Architects Group: organisation/technical-architects-group.md
    - Technical Governance Board: organisation/technical-governance-board.md
  - Resources:
    - resources/index.md
    - TNA Frontend: resources/tna-frontend.md
    - TNA Frontend Jinja: resources/tna-frontend-jinja.md
    - TNA Frontend Django: resources/tna-frontend-django.md
    - Design System: resources/design-system.md
    - GOV.UK Prototype Kit: resources/govuk-prototype-kit.md
    - Docker images: resources/docker-images.md
theme:
  name: material
  custom_dir: overrides
  favicon: https://raw.githubusercontent.com/nationalarchives/tna-frontend/main/src/nationalarchives/assets/images/favicon.ico
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - toc.integrate
  palette:
    - primary: custom
extra_css:
  - stylesheets/extra.css
plugins:
  - search
markdown_extensions:
  - abbr
  - attr_list
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
