site_name: Developer Handbook
site_url: https://nationalarchives.github.io/developer-handbook/
repo_url: https://github.com/nationalarchives/developer-handbook
dev_addr: 127.0.0.1:8888
nav:
  - Home: index.md
  - Getting started: getting-started.md
  - Technology:
    - Languages and tools: technology/index.md
    - HTML: technology/html.md
    - Python: technology/python.md
    - Java: technology/java.md
    - JavaScript: technology/javascript.md
    - TypeScript: technology/typescript.md
    - CSS: technology/css.md
    - Containers: technology/containers.md
  - Third party:
    - NPMJS: third-party/npmjs.md
    - PyPi: third-party/pypi.md
    - GitHub: third-party/github.md
    - Docker registries: third-party/docker-registries.md
    - Analytics: third-party/analytics.md
    - AWS: third-party/aws.md
  - Ways of working:
    - Service standard: ways-of-working/service-standard.md
    - Version control: ways-of-working/version-control.md
    - Testing: ways-of-working/testing.md
    - Browser support: ways-of-working/browser-support.md
    - Accessibility: ways-of-working/accessibility.md
    - Deployment: ways-of-working/deployment.md
  - Resources:
    - Frontend styles: resources/frontend-styles.md
    - Frontend implementations: resources/frontend-implementations.md
    - Docker images: resources/docker-images.md
theme:
  name: material
  logo: assets/tna-horizontal-logo.svg
  features:
    - navigation.sections
    - toc.integrate
  palette:
    - primary: custom
extra_css:
  - stylesheets/extra.css
plugins:
  - search
markdown_extensions:
  - abbr
  - attr_list
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
